### ISSUE TITLE
peerDependencies on v11.0.0 has peerdep @angular/cdk = 11.0.0

### ISSUE THREAD

**Issue by spike008t** [alvaro-octal/ngx-tour-md-menu#12]
Hey,

The package @ngx-tour/md-menu pushed on npmjs having a peerdep on @angular/cdk = 11.0.0.
Missing the ^carret on package.json pushed.

could you fix it?

Thank you!

**Comment by alvaro-octal** [comment]
Hi,

Could you check @ngx-tour/md-menu pushed@11.0.1?

**Comment by spike008t** [comment]
Thank you for your quick fix! That's better now.
I close the issue!
